"use client";

import React from "react";
import { motion } from "framer-motion";
import { 
  FileText, 
  User, 
  Home, 
  Truck, 
  Pill, 
  Users, 
  CheckCircle,
  Clock,
  Phone,
  MapPin,
  Calendar,
  Stethoscope,
  Heart
} from "lucide-react";

interface DischargePlanProps {
  patientInfo: any;
  shelterInfo: any;
  transportInfo: any;
  resourceInfo: any;
  pharmacyInfo: any;
  eligibilityInfo: any;
  socialWorkerInfo: any;
  vapiTranscription?: string;
}

const DischargePlan: React.FC<DischargePlanProps> = ({
  patientInfo,
  shelterInfo,
  transportInfo,
  resourceInfo,
  pharmacyInfo,
  eligibilityInfo,
  socialWorkerInfo,
  vapiTranscription
}) => {
  const currentDate = new Date().toLocaleDateString();
  const currentTime = new Date().toLocaleTimeString();

  return (
    <div className="max-w-4xl mx-auto p-6 bg-white">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-8 border-b pb-6"
      >
        <div className="flex items-center justify-center mb-4">
          <FileText className="w-8 h-8 text-blue-600 mr-3" />
          <h1 className="text-3xl font-bold text-gray-800">Medical Discharge Plan</h1>
        </div>
        <p className="text-gray-600">
          Generated by AI Social Worker • {currentDate} at {currentTime}
        </p>
      </motion.div>

      {/* Patient Information */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.1 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <User className="w-6 h-6 text-blue-600 mr-3" />
          Patient Information
        </h2>
        <div className="bg-gray-50 p-4 rounded-lg">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p><strong>Name:</strong> {patientInfo?.name || "Marcus Thompson"}</p>
              <p><strong>Date of Birth:</strong> {patientInfo?.dateOfBirth || "March 22, 1978"}</p>
              <p><strong>Age:</strong> {patientInfo?.age || "46 years"}</p>
              <p><strong>Gender:</strong> {patientInfo?.gender || "Male"}</p>
              <p><strong>Medical Record #:</strong> {patientInfo?.medicalRecordNumber || "MRN-5589243"}</p>
            </div>
            <div>
              <p><strong>Discharge Date:</strong> {patientInfo?.dischargeDateTime || "January 15, 2025 at 2:30 PM"}</p>
              <p><strong>Primary Diagnosis:</strong> {patientInfo?.primaryDiagnosis || "COPD exacerbation with respiratory distress"}</p>
              <p><strong>Secondary Diagnosis:</strong> {patientInfo?.secondaryDiagnosis || "Type 2 diabetes mellitus (uncontrolled), hypertension, chronic malnutrition"}</p>
              <p><strong>Housing Status:</strong> {patientInfo?.housingStatus || "Homeless - Undomiciled"}</p>
            </div>
          </div>
        </div>
      </motion.section>

      {/* Shelter Placement */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.2 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <Home className="w-6 h-6 text-green-600 mr-3" />
          Shelter Placement
        </h2>
        <div className="bg-green-50 p-4 rounded-lg border-l-4 border-green-500">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-lg font-semibold text-green-800">{shelterInfo?.name || "Harbor Light Center"}</h3>
              <p className="text-green-700">{shelterInfo?.address || "1275 Howard St, San Francisco, CA 94103"}</p>
              <p className="text-green-600 mt-2">
                <strong>Available Beds:</strong> {shelterInfo?.available_beds || "6-7"} | 
                <strong> Accessibility:</strong> {shelterInfo?.accessibility ? "Yes" : "No"} |
                <strong> Medical Respite:</strong> {shelterInfo?.services?.includes("medical_respite") ? "Yes" : "No"}
              </p>
              {vapiTranscription && (
                <div className="mt-3 p-3 bg-white rounded border">
                  <p className="text-sm text-gray-600"><strong>Verification Call:</strong></p>
                  <p className="text-sm italic">"{vapiTranscription}"</p>
                </div>
              )}
            </div>
            <CheckCircle className="w-6 h-6 text-green-500" />
          </div>
        </div>
      </motion.section>

      {/* Transportation */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.3 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <Truck className="w-6 h-6 text-blue-600 mr-3" />
          Transportation Arrangements
        </h2>
        <div className="bg-blue-50 p-4 rounded-lg border-l-4 border-blue-500">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <p><strong>Driver:</strong> {transportInfo?.driver || "Mike Johnson"}</p>
              <p><strong>Contact:</strong> {transportInfo?.phone || "(415) 555-1234"}</p>
              <p><strong>Vehicle:</strong> {transportInfo?.vehicle_type || "Wheelchair accessible medical transport"}</p>
            </div>
            <div>
              <p><strong>Pickup Time:</strong> {transportInfo?.pickup_time || "2:30 PM"}</p>
              <p><strong>Route:</strong> Hospital → {shelterInfo?.name || "Harbor Light Center"}</p>
              <p><strong>Estimated Duration:</strong> {transportInfo?.estimated_duration || "25 minutes"}</p>
            </div>
          </div>
        </div>
      </motion.section>

      {/* Resources & Supplies */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.4 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <Heart className="w-6 h-6 text-red-600 mr-3" />
          Resources & Supplies
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-red-50 p-4 rounded-lg border-l-4 border-red-500">
            <h3 className="font-semibold text-red-800 mb-2">Care Package</h3>
            <ul className="text-red-700">
              {(resourceInfo?.items || ["warm_winter_jacket", "thermal_underwear", "wool_socks_2_pairs", "waterproof_boots", "knit_hat", "gloves", "food_vouchers_3_days", "hygiene_kit"]).map((item: string, index: number) => (
                <li key={index} className="flex items-center">
                  <CheckCircle className="w-4 h-4 text-red-500 mr-2" />
                  {item.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase())}
                </li>
              ))}
            </ul>
            <p className="text-red-600 mt-2">
              <strong>Delivery:</strong> {resourceInfo?.delivery_address || "1275 Howard St, San Francisco, CA 94103"}
            </p>
          </div>
          
          <div className="bg-purple-50 p-4 rounded-lg border-l-4 border-purple-500">
            <h3 className="font-semibold text-purple-800 mb-2">Medications</h3>
            <ul className="text-purple-700">
              {(pharmacyInfo?.medications || [
                {"name": "Albuterol inhaler", "dosage": "90mcg", "frequency": "2 puffs every 4-6 hours as needed"},
                {"name": "Tiotropium bromide (Spiriva)", "dosage": "18mcg", "frequency": "1 inhalation daily"},
                {"name": "Prednisone", "dosage": "20mg", "frequency": "once daily for 5 days"},
                {"name": "Metformin", "dosage": "500mg", "frequency": "twice daily with meals"},
                {"name": "Lisinopril", "dosage": "10mg", "frequency": "once daily in morning"},
                {"name": "Aspirin", "dosage": "81mg", "frequency": "once daily"}
              ]).map((med: any, index: number) => (
                <li key={index} className="flex items-center">
                  <Pill className="w-4 h-4 text-purple-500 mr-2" />
                  {med.name} - {med.dosage} ({med.frequency})
                </li>
              ))}
            </ul>
            <p className="text-purple-600 mt-2">
              <strong>Pickup:</strong> {pharmacyInfo?.name || "SF General Hospital Pharmacy"} - {pharmacyInfo?.address || "1001 Potrero Ave, San Francisco, CA 94110"}
            </p>
          </div>
        </div>
      </motion.section>

      {/* Benefits & Eligibility */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.5 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <FileText className="w-6 h-6 text-orange-600 mr-3" />
          Benefits & Eligibility
        </h2>
        <div className="bg-orange-50 p-4 rounded-lg border-l-4 border-orange-500">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h3 className="font-semibold text-orange-800 mb-2">Verified Benefits</h3>
              <ul className="text-orange-700">
                {(eligibilityInfo?.benefits || ["Medi-Cal (Emergency enrollment)", "SNAP", "General Assistance"]).map((benefit: string, index: number) => (
                  <li key={index} className="flex items-center">
                    <CheckCircle className="w-4 h-4 text-orange-500 mr-2" />
                    {benefit}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <p><strong>Status:</strong> {eligibilityInfo?.status || "Verified"}</p>
              <p><strong>Case Worker:</strong> {eligibilityInfo?.case_worker || "Jane Smith"}</p>
              <p><strong>Contact:</strong> {eligibilityInfo?.phone || "(415) 555-5678"}</p>
            </div>
          </div>
        </div>
      </motion.section>

      {/* Social Worker Assignment */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.6 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <Users className="w-6 h-6 text-purple-600 mr-3" />
          Social Worker Assignment
        </h2>
        <div className="bg-purple-50 p-4 rounded-lg border-l-4 border-purple-500">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="text-lg font-semibold text-purple-800">
                {socialWorkerInfo?.assigned_worker || "Sarah Johnson"}
              </h3>
              <p className="text-purple-700">
                <strong>Department:</strong> {socialWorkerInfo?.department || "Social Work - SF General Hospital"}
              </p>
              <p className="text-purple-600">
                <strong>Contact:</strong> {socialWorkerInfo?.contact || "(415) 206-5555"}
              </p>
              <p className="text-purple-600">
                <strong>Follow-up:</strong> {socialWorkerInfo?.follow_up_scheduled || "2025-01-22T10:00:00"}
              </p>
              <p className="text-purple-600">
                <strong>Primary Care:</strong> {socialWorkerInfo?.primary_care_appointment || "Within 7 days (URGENT)"}
              </p>
              <p className="text-purple-600">
                <strong>Pulmonology:</strong> {socialWorkerInfo?.pulmonology_appointment || "Within 2 weeks"}
              </p>
            </div>
            <CheckCircle className="w-6 h-6 text-purple-500" />
          </div>
        </div>
      </motion.section>

      {/* Next Steps */}
      <motion.section
        initial={{ opacity: 0, x: -20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.7 }}
        className="mb-8"
      >
        <h2 className="text-2xl font-semibold text-gray-800 mb-4 flex items-center">
          <Calendar className="w-6 h-6 text-indigo-600 mr-3" />
          Next Steps & Follow-up
        </h2>
        <div className="bg-indigo-50 p-4 rounded-lg border-l-4 border-indigo-500">
          <ol className="text-indigo-700 space-y-2">
            <li className="flex items-center">
              <span className="bg-indigo-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">1</span>
              Patient will be transported to {shelterInfo?.name || "Harbor Light Center"} at {transportInfo?.pickup_time || "2:30 PM"}
            </li>
            <li className="flex items-center">
              <span className="bg-indigo-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">2</span>
              Care package and medications will be delivered to shelter
            </li>
            <li className="flex items-center">
              <span className="bg-indigo-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">3</span>
              Social worker {socialWorkerInfo?.assigned_worker || "Sarah Johnson"} will conduct follow-up assessment
            </li>
            <li className="flex items-center">
              <span className="bg-indigo-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm mr-3">4</span>
              Benefits verification and case management services will be initiated
            </li>
          </ol>
        </div>
      </motion.section>

      {/* Footer */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.8 }}
        className="text-center text-gray-500 text-sm border-t pt-4"
      >
        <p>This discharge plan was generated by AI agents and reviewed by {socialWorkerInfo?.assigned_worker || "Sarah Johnson"}, LCSW</p>
        <p>For questions, contact: {socialWorkerInfo?.contact || "(415) 555-5678"}</p>
      </motion.div>
    </div>
  );
};

export default DischargePlan;
